#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

picom --config ~/.config/picom/picom.conf &

clipmenud &

nitrogen --restore &

xss-lock --transfer-sleep-lock -- ~/.config/i3/scripts/lockscreen &

# Start NetworkManager applet
nm-applet &

# Get authentication working with polkit-gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xset s 480 dpms 600 86400 86400 &

# Start blueberry app for managing Bluetooth devices from tray
blueberry-tray &

# Start Flameshot for screenshots
flameshot &

# launch polybar
~/.config/polybar/launch.sh &

