#!/usr/bin/env bash

FG_COLOR="#bbbbbb"
BG_COLOR="#111111"
HLFG_COLOR="#111111"
HLBG_COLOR="#bbbbbb"
BORDER_COLOR="#222222"
ROFI_OPTIONS=(-theme ~/.config/rofi/power-profiles.rasi)
preferred_launcher="rofi"

launcher_list=(rofi zenity)

# Check if a command exists
command_exists() {
    command -v "$1" &> /dev/null
}

# Systemctl required
command_exists systemctl || exit 1

# Power profiles using asusctl
declare -A menu=(
    [ Performance]="asusctl profile -P Performance"
    [ Balanced]="asusctl profile -P Balanced"
    [ Power Saver]="asusctl profile -P Quiet"
)

menu_nrows=${#menu[@]}

# Prepare the launcher
prepare_launcher() {
    if [[ "$1" == "rofi" ]]; then
        launcher_exe="rofi"
        launcher_options=(-dmenu -i -lines "${menu_nrows}" "${ROFI_OPTIONS[@]}")
    elif [[ "$1" == "zenity" ]]; then
        launcher_exe="zenity"
        launcher_options=(--list --title="Power Profiles" --hide-header --column="")
    fi
}

for l in "${launcher_list[@]}"; do
    if command_exists "${l}"; then
        prepare_launcher "${l}"
        break
    fi
done

[[ -z "${launcher_exe}" ]] && exit 1

# Display the menu
selection=$(printf '%s\n' "${!menu[@]}" | sort | "${launcher_exe}" "${launcher_options[@]}")

# Apply the selected profile
[[ -n "${selection}" ]] && i3-msg -q "exec --no-startup-id ${menu[${selection}]}"

