font_family      JetBrains Mono Bold
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Bold Italic
bold_italic_font JetBrains Mono Bold Italic

font_size 10.0

text_composition_strategy legacy
# modify_font cell_width 95%

shell_integration no-cursor
enable_audio_bell no

confirm_os_window_close 0
# dynamic_background_opacity yes
hide_window_decorations no
# window_padding_width 0
# window_padding_height 0
# window_margin_width 22 0 0 0
placement_strategy top

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.15
cursor_shape block
cursor_blink true

repaint_delay 10
sync_to_monitor yes

disable_ligatures never
# include ./theme.conf

# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME

# Overrides
background_opacity 0.73
background_blur 10
